### ISSUE TITLE
Process must exit before requested information can be determined.

### ISSUE THREAD

**Issue by leonardseymore** [EntelectChallenge/2015-SpaceInvaders-TestHarness#15]
Hi,

The forum seems a bit buggy so I'm logging this here. The harness crashes when my bot either takes to long or prints too much, I can't say which, but I'm pretty sure it bombs before the 3 seconds are over. Surely a stupid bot shouldn't crash the harness anyway...thanks for the help

Something went wrong...
Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at ChallengeHarness.Runners.BotRunner.StartProcess(Process p) in c:\Dev\100K\2015-Sp
aceInvaders-TestHarness\ChallengeHarness\Runners\BotRunner.cs:line 208
   at ChallengeHarness.Runners.BotRunner.GetMove(MatchRender rendered) in c:\Dev\100K\2
015-SpaceInvaders-TestHarness\ChallengeHarness\Runners\BotRunner.cs:line 81
   at ChallengeHarness.Runners.MatchRunner.GetMove(BotRunner player, MatchRender render
ed) in c:\Dev\100K\2015-SpaceInvaders-TestHarness\ChallengeHarness\Runners\MatchRunner.
cs:line 67
   at ChallengeHarness.Runners.MatchRunner.Run() in c:\Dev\100K\2015-SpaceInvaders-Test
Harness\ChallengeHarness\Runners\MatchRunner.cs:line 54
   at SpaceInvadersDuel.Program.Main(String[] args) in c:\Dev\100K\2015-SpaceInvaders-T
estHarness\SpaceInvadersDuel\Program.cs:line 44

**Comment by mattpwest** [comment]
Hi Leonard,

Thanks for the bug report - indeed the harness should be able to survive a misbehaving bot!

It does sound like something that may have been fixed in the bot killing / return code reading code contributed by @bhaeussermann.

Could you please try the [new release](https://github.com/EntelectChallenge/2015-SpaceInvaders-TestHarness/releases) and let me know if that fixes it?

**Comment by Pyroseza** [comment]
Hi Matt, the new version (1.0.2) is still crashing. I can prevent the crash by forcing my bot to write "Nothing" if it does not decide on what to do.

**Comment by bhaeussermann** [comment]
@Indigodev The exception stack trace will have changed after the update. Could you give us the output that you get when it crashes with the new version?

**Comment by Pyroseza** [comment]
Sorry fellaz was my own mistake was trying to get the ships coordinates when I was actually "dead".
Not getting the silly error anymore just made sure to force a check if the ship was spawned or not.
if (this._player.ship != null) 
{ 
    //get coordinates
}
else
{
    //don't get coordinates silly human
}

**Comment by bhaeussermann** [comment]
:P
